apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: mq-git-repo
spec:
  params:
    - name: url
      value: 'https://github.com/ibm-cloudintegration/cp4i-mq-tekton'
    - name: revision
      value: "main"
  type: git
