apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: mq-trigger-template
spec:
  params:
    - name: MQ_PVC_SC
      #default: ibmc-file-gold-gid
      description: The storage class
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: mq-cp4i-pipelinerun-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: mq-pipeline
        params:
          - name: MQ_PVC_SC
            value: $(params.MQ_PVC_SC)
        resources:
          - name: source
            resourceRef:
              name: mq-git-repo
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mq-trigger-binding
spec:
  params:
  - name: MQ_PVC_SC
    value: ibmc-file-gold-gid
